name: Release Drafter

on:
  push:
    branches:
      - main
      - compose-1.6

jobs:
  update_draft_release:
    if: github.repository == 'fornewid/material-motion-compose'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
